version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2-sdk

    working_directory: ~/repo

    steps:
       - checkout

       - run:
           name: Unit Tests
           command: |
              ls
              dotnet build --framework=netcoreapp2.0 ResourceDirectory.sln
              dotnet test --framework=netcoreapp2.0 ResourceDirectory.sln
           
